workflows:
  my-workflow:
    instance_type: linux



workflows:
  my-workflow:
    scripts:
      - name: Build Android APK
        working_directory: android
        script: pwd
    artifacts:
      - app/build/outputs/**/**/*.apk
